name: Publish to npm

on:
  push:
    tags:
      - 'v*' # v1.0.0, v1.2.3 etc.

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Build zarr-maps-colormap
        run: npm run build:colormap

      - name: Publish zarr-maps-colormap
        run: npm publish --workspace=zarr-maps-colormap --access public

      - name: Build zarr-maps-tiling
        run: npm run build:tiling

      - name: Publish zarr-maps-tiling
        run: npm publish --workspace=zarr-maps-tiling --access public

      - name: Build zarr-maps-leaflet
        run: npm run build:leaflet

      - name: Publish zarr-maps-leaflet
        run: npm publish --workspace=zarr-maps-leaflet --access public

      - name: Build zarr-maps-ol
        run: npm run build:ol

      - name: Publish zarr-maps-ol
        run: npm publish --workspace=zarr-maps-ol --access public
